/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AboutView: typeof import('./src/views/AboutView.vue')['default']
    Answer: typeof import('./src/components/Answer.vue')['default']
    Earth3D: typeof import('./src/components/Earth3D.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MapBox: typeof import('./src/components/MapBox.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WonLost: typeof import('./src/components/WonLost.vue')['default']
  }
}
